// <auto-generated />
using System;
using DataAccessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessObjects.Migrations
{
    [DbContext(typeof(LibraryManagementDbContext))]
    [Migration("20260315052248_DBcontext")]
    partial class DBcontext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("BookID");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("AuthorID");

                    b.HasKey("BookId", "AuthorId")
                        .HasName("PK__BookAuth__6AED6DE6B5937920");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors", (string)null);
                });

            modelBuilder.Entity("BookCategory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("BookID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.HasKey("BookId", "CategoryId")
                        .HasName("PK__BookCate__9C705185A3AC1CD6");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuthorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuthorId")
                        .HasName("PK__Authors__70DAFC146E049A97");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime?>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BookId")
                        .HasName("PK__Books__3DE0C227DCD6DF1A");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "Isbn" }, "UQ__Books__447D36EAF96F4030")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BusinessObjects.Entities.BookCopy", b =>
                {
                    b.Property<int>("CopyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CopyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CopyId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("BookID");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("CopyId")
                        .HasName("PK__BookCopi__C26CCCE50337D64C");

                    b.HasIndex("BookId");

                    b.HasIndex(new[] { "Barcode" }, "UQ__BookCopi__177800D305EC2023")
                        .IsUnique();

                    b.ToTable("BookCopies");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A2B11B09F43");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Categori__8517B2E01FDA9B6A")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Fine", b =>
                {
                    b.Property<int>("FineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FineId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("FineDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LoanId")
                        .HasColumnType("int")
                        .HasColumnName("LoanID");

                    b.HasKey("FineId")
                        .HasName("PK__Fines__9D4A9BCC9DB4A575");

                    b.HasIndex(new[] { "LoanId" }, "UQ__Fines__4F5AD436A99F718A")
                        .IsUnique();

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LoanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<string>("BookTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CopyId")
                        .HasColumnType("int")
                        .HasColumnName("CopyID");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LoanDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ReaderId")
                        .HasColumnType("int");

                    b.Property<string>("ReaderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LoanId")
                        .HasName("PK__Loans__4F5AD43757D5E2B7");

                    b.HasIndex("CopyId");

                    b.HasIndex("ReaderId");

                    b.HasIndex("UserId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Reader", b =>
                {
                    b.Property<int>("ReaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReaderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReaderId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("MembershipDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReaderId")
                        .HasName("PK__Readers__8E67A58161E77ED4");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CardNumber" }, "UQ__Readers__A4E9FFE9D0906913")
                        .IsUnique();

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("BusinessObjects.Entities.ReaderComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CommentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("BookID");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CommentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ReaderId")
                        .HasColumnType("int")
                        .HasColumnName("ReaderID");

                    b.HasKey("CommentId")
                        .HasName("PK__ReaderCo__C3B4DFAAF70E10BE");

                    b.HasIndex("BookId");

                    b.HasIndex("ReaderId");

                    b.ToTable("ReaderComments");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3AFF4FD502");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160AD07F913")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BusinessObjects.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC8D7913B3");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534E52D3018")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookAuthor", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookAuthors_Authors");

                    b.HasOne("BusinessObjects.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookAuthors_Books");
                });

            modelBuilder.Entity("BookCategory", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookCategories_Books");

                    b.HasOne("BusinessObjects.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookCategories_Categories");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Book", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Books_Categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObjects.Entities.BookCopy", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookCopies_Books");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Fine", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Loan", "Loan")
                        .WithOne("Fine")
                        .HasForeignKey("BusinessObjects.Entities.Fine", "LoanId")
                        .IsRequired()
                        .HasConstraintName("FK_Fines_Loans");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Loan", b =>
                {
                    b.HasOne("BusinessObjects.Entities.BookCopy", "Copy")
                        .WithMany("Loans")
                        .HasForeignKey("CopyId")
                        .IsRequired()
                        .HasConstraintName("FK_Loans_BookCopies");

                    b.HasOne("BusinessObjects.Entities.Reader", "Reader")
                        .WithMany()
                        .HasForeignKey("ReaderId");

                    b.HasOne("BusinessObjects.Entities.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Loans_Users");

                    b.Navigation("Copy");

                    b.Navigation("Reader");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Reader", b =>
                {
                    b.HasOne("BusinessObjects.Entities.User", "User")
                        .WithMany("Readers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Readers_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.Entities.ReaderComment", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Book", "Book")
                        .WithMany("ReaderComments")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("FK_ReaderComments_Books");

                    b.HasOne("BusinessObjects.Entities.Reader", "Reader")
                        .WithMany("ReaderComments")
                        .HasForeignKey("ReaderId")
                        .IsRequired()
                        .HasConstraintName("FK_ReaderComments_Readers");

                    b.Navigation("Book");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("BusinessObjects.Entities.User", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Book", b =>
                {
                    b.Navigation("BookCopies");

                    b.Navigation("ReaderComments");
                });

            modelBuilder.Entity("BusinessObjects.Entities.BookCopy", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Loan", b =>
                {
                    b.Navigation("Fine");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Reader", b =>
                {
                    b.Navigation("ReaderComments");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusinessObjects.Entities.User", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Readers");
                });
#pragma warning restore 612, 618
        }
    }
}
